// Generated by ReMap for R5Flowstate.
// Source code: https://github.com/ReMap
// Do not edit this file directly; rebuild it from the ReMap sources.

/*
 * ReMap game scripts
 *
 * Source lineage: rewritten from the active R5Reloaded ReMap implementation
 * and the legacy ReMap scripts.
 * Original ReMap: Zee (@AyeZeeBB on X, zee_x64 on Discord)
 * and Julefox (@Julefox_ on X, julefox on Discord).
 * This standalone ReMap rewrite was created and is maintained by Julefox.
 *
 * Made with love for the Apex modding community. <3
 * Built on the Apex modding foundation created by Amos (@AmosModz on X, amosmodz on Discord):
 * https://github.com/Mauler125/r5sdk
 */

global function Sv_ReMap_LoadMap

void function Sv_ReMap_LoadMap() {
	if ( GetMapName() != "mp_rr_desertlands_hu" )
		return

	Sh_ReMap_Clear()

	// Ziplines
	ReMap_CreateZipline( <6168.5273, 7942.4063, -3962>, <0, -20, 0>, <6116.2446, 7956.647, -4249.4111>, <0, -20, 0>, REMAP_ZIPLINE_END_SUPPORT, REMAP_ZIPLINE_END_NONE, true, 2, 1, 230, 180, true, 1, 45, -1, 1, false, true, 100, 100, false, false, false )
	ReMap_CreateZipline( <9148.3545, 5727.1343, -3568>, <0, 90, 0>, <4944.8276, 5935.6455, -3829.155>, <0, 90, 0>, REMAP_ZIPLINE_END_SUPPORT, REMAP_ZIPLINE_END_ARM, false, 2, 1, 180, 180, true, 1, 0, -1, 1, false, true, 100, 100, false, false, false )
}
